'use client'

import { useState } from 'react'
import { matches } from '@/lib/data'
import { formatDate } from '@/lib/utils'
import { timezones } from '@/lib/data'

export default function ScheduleGeneratorPage() {
  const [selectedTimezone, setSelectedTimezone] = useState('UTC')
  const [paperSize, setPaperSize] = useState<'A4' | 'A3'>('A4')
  const [includeGroups, setIncludeGroups] = useState<string[]>(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])
  const [isGenerating, setIsGenerating] = useState(false)

  const generatePDF = async () => {
    setIsGenerating(true)

    // Simulate PDF generation delay
    await new Promise((resolve) => setTimeout(resolve, 1500))

    // In production, this would use jsPDF + html2canvas
    // For now, we'll create a printable HTML version
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>World Cup 2026 Schedule</title>
          <style>
            @page { size: ${paperSize.toLowerCase()}; margin: 1cm; }
            body { font-family: Arial, sans-serif; font-size: 10px; }
            h1 { font-size: 18px; text-align: center; margin-bottom: 20px; }
            h2 { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #333; padding-bottom: 5px; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th, td { border: 1px solid #ccc; padding: 6px; text-align: left; }
            th { background: #f5f5f5; }
            .match-time { font-weight: bold; }
            @media print { body { print-color-adjust: exact; -webkit-print-color-adjust: exact; } }
          </style>
        </head>
        <body>
          <h1>⚽ FIFA World Cup 2026 - Complete Schedule</h1>
          <p style="text-align: center; color: #666; margin-bottom: 30px;">
            Timezone: ${timezones.find(t => t.value === selectedTimezone)?.label || 'UTC'} |
            Paper: ${paperSize} |
            Generated: ${new Date().toLocaleDateString()}
          </p>
          ${['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
            .filter(g => includeGroups.includes(g))
            .map(group => `
              <h2>Group ${group}</h2>
              <table>
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Match</th>
                    <th>Venue</th>
                  </tr>
                </thead>
                <tbody>
                  ${matches
                    .filter(m => m.group === group)
                    .map(m => `
                      <tr>
                        <td>${formatDate(m.date)}</td>
                        <td class="match-time">${m.time}</td>
                        <td>${m.homeTeam} vs ${m.awayTeam}</td>
                        <td>${m.venue}, ${m.city}</td>
                      </tr>
                    `).join('')}
                </tbody>
              </table>
            `).join('')}
          <p style="text-align: center; margin-top: 30px; font-size: 9px; color: #999;">
            Generated by World Cup 2026 Tool Hub | www.statshubs.net
          </p>
        </body>
        </html>
      `)
      printWindow.document.close()
      setTimeout(() => {
        printWindow.print()
      }, 500)
    }

    setIsGenerating(false)
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="container mx-auto px-4">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">📅 World Cup 2026 Printable Schedule</h1>
          <p className="text-gray-600">
            Generate and download a printable PDF schedule for the 2026 World Cup.
            Choose your timezone and paper size for the perfect printout.
          </p>
        </div>

        {/* Options */}
        <div className="bg-white rounded-lg p-6 mb-8 shadow-sm">
          <h2 className="text-xl font-bold mb-4">Schedule Options</h2>

          <div className="grid md:grid-cols-3 gap-6">
            {/* Timezone */}
            <div>
              <label className="block text-sm font-medium mb-2">Timezone</label>
              <select
                value={selectedTimezone}
                onChange={(e) => setSelectedTimezone(e.target.value)}
                className="w-full border rounded-lg px-4 py-2"
              >
                {timezones.map((tz) => (
                  <option key={tz.value} value={tz.value}>
                    {tz.label} ({tz.offset})
                  </option>
                ))}
              </select>
            </div>

            {/* Paper Size */}
            <div>
              <label className="block text-sm font-medium mb-2">Paper Size</label>
              <div className="flex gap-4">
                <label className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="paperSize"
                    value="A4"
                    checked={paperSize === 'A4'}
                    onChange={() => setPaperSize('A4')}
                    className="w-4 h-4"
                  />
                  A4 (Standard)
                </label>
                <label className="flex items-center gap-2">
                  <input
                    type="radio"
                    name="paperSize"
                    value="A3"
                    checked={paperSize === 'A3'}
                    onChange={() => setPaperSize('A3')}
                    className="w-4 h-4"
                  />
                  A3 (Large)
                </label>
              </div>
            </div>

            {/* Groups */}
            <div>
              <label className="block text-sm font-medium mb-2">Include Groups</label>
              <div className="flex flex-wrap gap-2">
                {['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'].map((group) => (
                  <label key={group} className="flex items-center gap-1 text-sm">
                    <input
                      type="checkbox"
                      checked={includeGroups.includes(group)}
                      onChange={(e) => {
                        if (e.target.checked) {
                          setIncludeGroups([...includeGroups, group])
                        } else {
                          setIncludeGroups(includeGroups.filter((g) => g !== group))
                        }
                      }}
                      className="w-4 h-4"
                    />
                    {group}
                  </label>
                ))}
              </div>
            </div>
          </div>

          <button
            onClick={generatePDF}
            disabled={isGenerating || includeGroups.length === 0}
            className="mt-6 bg-blue-600 text-white px-8 py-3 rounded-lg font-semibold hover:bg-blue-700 transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed"
          >
            {isGenerating ? 'Generating PDF...' : '📄 Generate & Print PDF'}
          </button>
        </div>

        {/* Preview */}
        <div className="bg-white rounded-lg p-6 shadow-sm">
          <h2 className="text-xl font-bold mb-4">Schedule Preview</h2>
          <div className="space-y-4">
            {matches.slice(0, 6).map((match) => (
              <div key={match.id} className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className={`px-2 py-1 rounded text-xs font-medium bg-blue-100 text-blue-800`}>
                      Group {match.group}
                    </span>
                    <span className="text-sm text-gray-600">{formatDate(match.date)}</span>
                  </div>
                  <p className="font-semibold">
                    {match.homeTeam} vs {match.awayTeam}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-xl font-bold text-blue-600">{match.time}</p>
                  <p className="text-sm text-gray-600">{match.venue}</p>
                </div>
              </div>
            ))}
          </div>
          <p className="text-center text-sm text-gray-500 mt-4">
            Showing first 6 matches. Full schedule will be in the generated PDF.
          </p>
        </div>

        {/* SEO Content */}
        <div className="mt-12 bg-white rounded-lg p-8 shadow-sm">
          <h2 className="text-2xl font-bold mb-4">How to Use the Printable Schedule</h2>
          <div className="prose max-w-none">
            <p className="mb-4">
              Our World Cup 2026 printable schedule generator allows you to create a customized PDF schedule
              that you can print and take anywhere. Whether you're planning a watch party, organizing a trip
              to the stadium, or just want to keep track of match times, our tool has you covered.
            </p>

            <h3 className="text-xl font-semibold mt-6 mb-3">Features</h3>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li><strong>Customizable Timezone:</strong> Show times in your local timezone</li>
              <li><strong>Paper Size Options:</strong> A4 for standard printers, A3 for larger displays</li>
              <li><strong>Group Filtering:</strong> Print all groups or just your favorites</li>
              <li><strong>High Quality:</strong> Clean, readable format optimized for printing</li>
              <li><strong>Free Download:</strong> No watermarks, no sign-up required</li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3">Use Cases</h3>
            <div className="grid md:grid-cols-2 gap-4 mb-4">
              <div>
                <h4 className="font-semibold mb-2">📍 For Stadium Visitors</h4>
                <p className="text-sm text-gray-600">
                  Keep track of which matches you're attending and plan your travel accordingly.
                  Print multiple copies for your group.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">🍺 For Watch Parties</h4>
                <p className="text-sm text-gray-600">
                  Post the schedule on your wall so everyone knows when to show up.
                  Great for bars, offices, or home gatherings.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">✈️ For Travelers</h4>
                <p className="text-sm text-gray-600">
                  Print schedules for different timezones if you're visiting multiple regions.
                  Stay organized across time zones.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">🏫 For Teachers & Students</h4>
                <p className="text-sm text-gray-600">
                  Educational resource for discussing global events, time zones, and international sports.
                </p>
              </div>
            </div>

            <h3 className="text-xl font-semibold mt-6 mb-3">Print Tips</h3>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li>Use high-quality paper for best results</li>
              <li>Enable "Print background graphics" in your printer settings</li>
              <li>Consider laminating for durability</li>
              <li>Print in color if possible for better readability</li>
            </ul>
          </div>
        </div>

        {/* Related Tools */}
        <div className="mt-8 grid md:grid-cols-3 gap-4">
          <a href="/tools/timezone-converter" className="tool-card bg-white rounded-lg p-4 border text-center">
            <div className="text-2xl mb-2">🌍</div>
            <h4 className="font-semibold">Time Zone Converter</h4>
            <p className="text-sm text-gray-600">Convert match times</p>
          </a>
          <a href="/tools/bracket-maker" className="tool-card bg-white rounded-lg p-4 border text-center">
            <div className="text-2xl mb-2">🏆</div>
            <h4 className="font-semibold">Bracket Maker</h4>
            <p className="text-sm text-gray-600">Predict tournament results</p>
          </a>
          <a href="/tools/standings" className="tool-card bg-white rounded-lg p-4 border text-center">
            <div className="text-2xl mb-2">📊</div>
            <h4 className="font-semibold">Standings Tracker</h4>
            <p className="text-sm text-gray-600">Track live standings</p>
          </a>
        </div>
      </div>
    </div>
  )
}
